export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";

export const REQUEST_HOTELS_PENDING = "REQUEST_HOTELS_PENDING";
export const REQUEST_HOTELS_SUCCESS = "REQUEST_HOTELS_SUCCESS";
export const REQUEST_HOTELS_FAILED = "REQUEST_HOTELS_FAILED";